name: Set up environment
description: Sets up environment
inputs:
  packages:
    description: APT package names
    required: false
runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      name: Get APT packages
      id: apt-packages
      run: |
        packages=(${{ inputs.packages }})
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          cmake \
          ninja-build \
          xvfb \
          gcc \
          g++ \
          "${packages[@]}"
      shell: bash