name: build
on:
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          MATRIX=$(jq -c . matrix.json)
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
  build:
    needs: prepare-matrix
    name: ${{ matrix.os }} - ${{ matrix.arch }} - ${{ matrix.toolchain }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Clone
        run: git clone https://github.com/webview/webview.git
      - name: Unpack
        if: ${{ runner.os != 'Windows' }}
        run: |
          rm -rf webview/.github webview/README.md
          mv webview/* .
      - name: Unpack (windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          rd -r "webview/.github"
          rm "webview/README.md"
          mv webview/* .
      - name: Setup
        uses: ./.github/actions/setup-env
        with:
          packages: ${{ matrix.packages }}
      